"""empty message

Revision ID: 35c0ef63907c
Revises: b36df4685afd
Create Date: 2020-05-02 00:37:39.479637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35c0ef63907c"
down_revision = "b36df4685afd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatrooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("messages", sa.Column("room_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "messages", "chatrooms", ["room_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "room_id")
    op.drop_table("chatrooms")
    # ### end Alembic commands ###
