"""empty message

Revision ID: d3edb9571b92
Revises: 35c0ef63907c
Create Date: 2020-05-02 00:50:03.011354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3edb9571b92"
down_revision = "35c0ef63907c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("chatroom_id", sa.Integer(), nullable=True))
    op.drop_constraint("messages_room_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(None, "messages", "chatrooms", ["chatroom_id"], ["id"])
    op.drop_column("messages", "room_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("room_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_room_id_fkey", "messages", "chatrooms", ["room_id"], ["id"]
    )
    op.drop_column("messages", "chatroom_id")
    # ### end Alembic commands ###
